### ISSUE TITLE
Corrigir Issue no (index.js)

### ISSUE THREAD

**Issue by hallancma** [ggalmeida1/jobify#1]
No arquivo index.js

Na linha 23 alterar de :

    response.render ('home', {
        categorias
    })

Para : 
  response.render('home', {
    categorias,
    vagas
  });

Na linha 30 alterar de :  
app.get('/vaga', (request, response) => {
    response.render ('vaga', {
    })

})

Para:
app.get('/vaga/:id', async (request, response) => {
  //console.log(request.params);
  const idVaga = request.params.id;
  const db = await dbConnection;
  const vaga = await db.get(`select * from vagas where id = ${idVaga};`);
  console.log(vaga);
  response.render('vaga', {
    vaga
  });
});

Na linha 36 alterar de : 

app.get('/vaga/:id', async (request, response) => {
  //console.log(request.params);
  const idVaga = request.params.id;
  const db = await dbConnection;
  const vaga = await db.get(`select * from vagas where id = ${idVaga};`);
  console.log(vaga);
  response.render('vaga', {
    vaga
  });
});

Para:  
const init = async () => {
  const db = await dbConnection;
  await db.run(
    'create table if not exists categorias (id INTEGER PRIMARY KEY, categoria TEXT);'
  );
  await db.run(
    'create table if not exists vagas (id INTEGER PRIMARY KEY, categoria INTEGER, titulo TEXT, descricao TEXT);'
  );
  await db.run(`delete from vagas`);
  await db.run(`delete from categorias`);
  const categoria = 'Marketing team';
  await db.run(`insert into categorias(categoria) values('${categoria}')`);
  const vaga = 'Marketing Digital (San Francisco)';
  const descricao = 'vaga para Marketing Digital';
  await db.run(
    `insert into vagas(categoria, titulo, descricao) values(1, '${vaga}', '${descricao}')`
  );
};
Ps: Na segunda vez que for rodar comentar as linhas que deletam e insere as categorias e vagas, pois no decorrer do curso vc vai inseri-las direto pela aplicação.

**Comment by ggalmeida1** [comment]
Maravilha, alterando aqui. Obrigado!

**Comment by ggalmeida1** [comment]
Está dando um erro ao rodar o node:
➜  jobify git:(master) ✗ node index.js
jobify/index.js:33
    const db = await dbConnection;
               ^^^^^

SyntaxError: await is only valid in async function
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11

**Comment by ggalmeida1** [comment]
alterado
