### ISSUE TITLE
Correção arquivo vaga.ejs

### ISSUE THREAD

**Issue by hallancma** [ggalmeida1/jobify#2]
Na linha 3 alterar de:

<h2>Fullstack Developer (Remote)</h2>
<div>
    <h3> Engineering team</h3>
    <ul>
        <li><a href="vaga"> Fullstack Developer (Remote)</a></li>
    </ul>
</div>

<div>
    <h3> Marketing team</h3>
    <ul>
        <li><a href=""> Digital Marketing (San Francisco)</a></li>
    </ul>
</div>
<%- include ('footer') %>

Para:

<h2><%- vaga.titulo %></h2>
  <div>
    
    <ul>
      <li><%- vaga.descricao %></li>
    </ul>
   
  </div>
<%- include ('footer') %>

**Comment by ggalmeida1** [comment]
Alterado.
