### ISSUE TITLE
Correção arquivo header.ejs

### ISSUE THREAD

**Issue by hallancma** [ggalmeida1/jobify#3]
Na linha 9 alterar de:
<link href="estilos.css" rel="stylesheet">
Para:
<link href="/estilos.css" rel="stylesheet">

Na linha 14 alterar de:
 <h1><a href="/"> <img src="images/logo.png" alt="Jobify - by DevPleno" width="404px" height="178px"></a></h1>
Para:
<h1><a href="/"> <img src="/images/logo.png" alt="Jobify - by DevPleno" width="404px" height="178px"></a></h1>

**Comment by ggalmeida1** [comment]
Alterado e corrigido
