### ISSUE TITLE
Index.js Corrigido Completo

### ISSUE THREAD

**Issue by hallancma** [ggalmeida1/jobify#4]
const express = require('express');
const app = express();
const sqlite = require('sqlite');
const dbConnection = sqlite.open('banco.sqlite', { Promise });

app.set('view engine', 'ejs');
app.use(express.static('public'));

app.get('/', async (request, response) => {
  const db = await dbConnection;
  const categoriasDb = await db.all('select * from categorias;');
  const vagas = await db.all('select * from vagas');
  const categorias = categoriasDb.map(cat => {
    return {
      ...cat,
      vagas: vagas.filter(vaga => vaga.categoria === cat.id)
    };
  });
  response.render('home', {
    categorias,
    vagas
  });
});

app.get('/vaga/:id', async (request, response) => {
  //console.log(request.params);
  const idVaga = request.params.id;
  const db = await dbConnection;
  const vaga = await db.get(`select * from vagas where id = ${idVaga};`);
  console.log(vaga);
  response.render('vaga', {
    vaga
  });
});

const init = async () => {
  const db = await dbConnection;
  await db.run(
    'create table if not exists categorias (id INTEGER PRIMARY KEY, categoria TEXT);'
  );
  await db.run(
    'create table if not exists vagas (id INTEGER PRIMARY KEY, categoria INTEGER, titulo TEXT, descricao TEXT);'
  );
  await db.run(`delete from vagas`);
  await db.run(`delete from categorias`);
  const categoria = 'Marketing team';
  await db.run(`insert into categorias(categoria) values('${categoria}')`);
  const vaga = 'Marketing Digital (San Francisco)';
  const descricao = 'vaga para Marketing Digital';
  await db.run(
    `insert into vagas(categoria, titulo, descricao) values(1, '${vaga}', '${descricao}')`
  );
};

init();

app.listen(8000, err => {
  if (err) {
    console.log('Não foi possivel iniciar o servidor do jobify');
  } else {
    console.log('servidor do jobify rodando');
  }
});

**Comment by ggalmeida1** [comment]
faltou declarar o async na linha app.get('/vaga/:id', async (request, response) => {
